### ISSUE TITLE
add link for alumni on people page 

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#74]
Have come around to wanting to be able to include a single, user-specified "permalink" of sorts (e.g. researchgate, google scholar, linkedin, github, etc...) for lab alumni. Not sure how to include it on the page but maybe we can make the photo or the entire square for an individual clickable? Or include a little "url" icon? open to suggestions on that.

**Comment by katiehouse3** [comment]
I think making the entire box clickable could look really cool! I'll mock something up today and we can review it at our meeting.

**Comment by nickreich** [comment]
Before I added this link, wanted to make sure I wasn't going to break some iconification. Justin Baldwin has a researchgate link: https://www.researchgate.net/profile/Justin_Baldwin Is there an RG icon? what is the logic for the new little icons for people page links?

**Comment by katiehouse3** [comment]
There is not a researchgate icon, although you wouldn't need one for Justin because he is an alumni. 

Everything is the same except in the team.yml you change the name of the link with the icon name:
`links:
    - name: <ICON NAME>`

Here is a list that maps the icon with the specific Icon name:
- **Google Scholar**:  ai ai-google-scholar-square ai-2x
- **Twitter**:  flaticon-twitter-1
- **Resume**: flaticon-curriculum
- **Website**: flaticon-laptop-1
- **Github**: flaticon-github-1

However, Alumni Links must always follow this format:
` 
links:
    - name: alumni_link
      url: "<URL>"
`

I will add this to the website README!
